language: python
python: 2.7
sudo: false
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=flake8
install:
    - pip install coverage nose mock python-coveralls tox
script:
    - tox -e $TOX_ENV
after_success:
    - coveralls
notifications:
    irc: "irc.freenode.org#rpappalax"
